Trying to use another way to remove comment
Signed-off-by: Kakadu <Kakadu@pm.me>
Signed-off-by: Dmitrii.Kosarev a.k.a. Kakadu Dmitrii.Kosarev@pm.me <Kakadu@pm.me>

diff --git a/.github/workflows/PRformat.yml b/.github/workflows/PRformat.yml
--- a/.github/workflows/PRformat.yml
+++ b/.github/workflows/PRformat.yml
@@ -51,7 +51,41 @@ jobs:
           cd ${{ env.latest }} && python3 ../lint_filesystem.py ${{ env.latest }}
 
       - name: Checking ocamlformat
+        id: check-ocamlformat
+        continue-on-error: true
         run: |
-          cd ${{ env.latest }} && opam exec -- dune build @fmt --profile=release
+          echo "PROPERLY_FORMATTED=y" >> $GITHUB_ENV
+          cd ${{ env.latest }} && opam exec -- dune build @fmt --profile=release || echo "PROPERLY_FORMATTED=n" >> $GITHUB_ENV
 
       # TODO: onfail post a comment how to fix it
+
+      - name: Find a comment with OCamlformat report
+        uses: peter-evans/find-comment@v2
+        id: fc
+        with:
+          issue-number: ${{ github.event.number }}
+          body-includes: OCamlformat report for
+          comment-author: github-actions[bot]
+
+      - name: Remove comment if build is OK and a comment was found
+        if: steps.fc.outputs.comment-id != 0
+        #if: steps.check-ocamlformat.outputs.exit_code == 0 && steps.fc.outputs.comment-id != 0
+        run: |
+          curl -L https://api.github.com/repos/Kakadu/fp2023/pulls/comments/${{ steps.fc.outputs.comment-id }} \
+            -X DELETE -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28"
+
+      # TODO: move to workflow with proper authorization
+      #- name: Create comment
+      #  if: ${{ env.PROPERLY_FORMATTED == 'n' }}
+      #  uses: peter-evans/create-or-update-comment@v1
+      #  with:
+      #    edit-mode: replace
+      #    issue-number: ${{ github.event.number }}
+      #    body: |
+      #      ### OCamlformat report for ${{ env.latest }}
+
+      #      Format check failed. It could have two reasons:
+      #      * You didn't configure VsCode extensions properly
+      #      * The versions of ocamlformat differ on your machine and on CI
